# Use Node.js base image
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy the rest of the code
COPY . .

# Build Next.js app
RUN npm run build

# Expose the frontend port
EXPOSE 3000

# Run the Next.js server
CMD ["npm", "start"]
