# Dockerfile.frontend

FROM node:18-alpine

WORKDIR /usr/src/app

# Copy dependency manifest
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY . .

# Build the React app
RUN npm run build

# Serve using a static file server
RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
