import type { Metadata } from "next";
import Header from "@/components/Header"
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";


export const metadata: Metadata = {
  title: "eSim Unlimited",
  description: "Generated by create next app",
};
async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body
        className={`font-roboto antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <Header/>
          {children}
          <Navbar/>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}

export default RootLayout
