import type { Metadata } from "next";
import Header from "@/components/Header"
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { AuthProvider } from "@/components/AuthProvider/AuthProvider";
import Script from "next/script";


export const metadata: Metadata = {
  title: "eSim Unlimited",
  description: "Generated by create next app",
};
async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body
        className={`font-roboto antialiased bg-mainbg`}
      >
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive" // или 'afterInteractive', если не критично
        />
        <AuthProvider>
          <NextIntlClientProvider messages={messages}>
            <Header/>
            {children}
            <Navbar/>
          </NextIntlClientProvider>
        </AuthProvider>


      </body>
    </html>
  );
}

export default RootLayout
